package d101evidencetransport

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"math"
	"strings"
	"testing"
)

func TestEvidenceCanonicalScopePreservesOriginalHashSeparation(t *testing.T) {
	scope := evidenceScopeFixture()
	compact, _ := json.Marshal(scope)
	indented, _ := json.MarshalIndent(scope, "", "  ")
	if sha256.Sum256(compact) == sha256.Sum256(indented) {
		t.Fatal("fixture original hashes equal")
	}
	first, err := DecodeScope(compact)
	second, secondErr := DecodeScope(indented)
	if err != nil || secondErr != nil {
		t.Fatal("valid original formatting refused")
	}
	firstSHA, err := ScopeDigest(first)
	secondSHA, secondErr := ScopeDigest(second)
	if err != nil || secondErr != nil || firstSHA != secondSHA {
		t.Fatal("derived scope digest depends on original formatting")
	}
	// The expected digest below is generated by C9's Python encoding:
	// json.dumps(scope, ensure_ascii=False, sort_keys=True, separators=(',', ':')).
	if firstSHA != "a136a506b2e56858b8c821dada22153387661721d1772e90f89f78724d9d7049" {
		t.Fatal("scope digest differs from C9 encoding")
	}
}

func TestEvidenceCanonicalScopeKeepsUnsignedBudgetAndRejectsInvalidScope(t *testing.T) {
	scope := evidenceScopeFixture()
	scope.SpaceBudget.BackupBytes = math.MaxUint64 - existingDiskReserveBytes
	scope.SpaceBudget.NewFileCount = math.MaxUint64
	wire, err := CanonicalScopeBytes(scope)
	if err != nil || bytes.Contains(wire, []byte("\n")) || !strings.Contains(string(wire), `"NewFileCount":18446744073709551615`) ||
		!strings.Contains(string(wire), `"BackupBytes":18446744062972133375`) {
		t.Fatal("canonical encoding lost uint64 precision")
	}
	scope.TypedTargetRef.SHA256 = strings.Repeat("f", 64)
	if _, err := CanonicalScopeBytes(scope); err == nil {
		t.Fatal("invalid scope was normalized into usable bytes")
	}
}
